spring.application.name=EmailSender
# Email SMTP Configuration (Example: Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ombade364@gmail.com
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Scheduled Timezone
spring.task.scheduling.pool.size=1
spring.task.scheduling.thread-name-prefix=scheduler-
